baseURL = "https://4ft35t.github.io/"
languageCode = "zh-CN"
title = "4ft35t blog"
theme = "maupassant"
googleAnalytics = "UA-163577388-1"

[author]
  name = "af.test"

[params]
  author = '4ft35t'
  subtitle = "折腾笔记"
  keywords = "openwrt, lede, router, android, linux"
  description = "随手折腾，顺手记录"

[menu]
  [[menu.main]]
    identifier = "archives"
    name = "归档"
    url = "/archives/"
    weight = 2
  [[menu.main]]
    identifier = "about"
    name = "关于"
    url = "/about/"
    weight = 3

[params.utteranc]
    enable = true
    repo = "4ft35t/4ft35t.github.io"    # 存储评论的Repo，格式为 owner/repo
    issueTerm = "pathname"  #表示你选择以那种方式让github issue的评论和你的文章关联。
    theme = "github-light" # 样式主题，有github-light和github-dark两种

[markup]
  [markup.highlight]
      lineNos = true
      style = "github"
